server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm_saas?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 跨域配置（前端访问必开）
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  # 下划线转驼峰（必须开）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印SQL
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web: DEBUG